# Generated by Django 3.2.7 on 2022-05-29 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=500)),
                ('clientname', models.CharField(max_length=500)),
                ('server', models.CharField(max_length=100)),
                ('paymentRecieved', models.CharField(max_length=100)),
                ('paymentType', models.CharField(max_length=100)),
                ('profit', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
            ],
        ),
    ]
